myauth/urls.py
from django.urls import path
#from django.contrib.auth.views import LoginView
from myauth.views import (
    AboutMeView, 
    RegisterView,
    get_cookie_view,
    FooBarView
    )


app_name = 'myauth'

urlpatterns = [
    path('about-me/', AboutMeView.as_view(), name="about-me"),
    path('register/', RegisterView.as_view(), name="register"),
    path('cookie/get/', get_cookie_view, name="cookie-get"),
    path('boo-bar/', FooBarView.as_view(), name="foo-bar"),
      

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls', namespace='shopapp')),
    path('req/', include('requestdataapp.urls', namespace='requestdataapp')),
    path('myauth/', include('myauth.urls', namespace='myauth')),
    path('accounts/login/', 
        LoginView.as_view(
        template_name="myauth/login.html",
        redirect_authenticated_user=True,
        ),
         name="login"),
    path('accounts/logout/',
        LogoutView.as_view(
        # next_page=reverse_lazy("login")
        ),
        name='logout'),

]

shopapp/urls.py
from django.urls import path
from .views import (ShopIndexView,
                    GroupsListView,
                    ProductDetailView,
                    ProductsListView,
                    ProductCreateView,
                    ProductUpdateView,
                    ProductDeleteView,
                    ProductArchivedView,
                    OrdersListView,
                    OrderDetailView,
                    OrderCreateView,
                    OrderDeleteView,
                    OrderUpdateView,
                    ProductsDataExportView,
                    OrderExportView
                    )


# from shopapp.views import first_page

app_name = 'shopapp'

urlpatterns = [
    path('', ShopIndexView.as_view(), name='index'),
    path('groups/', GroupsListView.as_view(), name='groups-list'),
    path('products/', ProductsListView.as_view(), name='product-list'),
    path('products/export/', ProductsDataExportView.as_view(), name='product-export'),
    path('products/create/', ProductCreateView.as_view(), name='product-create'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('products/<int:pk>/update/',
         ProductUpdateView.as_view(), name='product-update'),
    path('products/<int:pk>/delete/',
         ProductDeleteView.as_view(), name='product-delete'),
    path('products/<int:pk>/archived/',
         ProductArchivedView.as_view(), name='product-archived'),
    path('orders/', OrdersListView.as_view(), name='order-list'),
    path('orders/create', OrderCreateView.as_view(), name='order-create'),
    path('orders/export', OrderExportView.as_view(), name='order-export'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order-detail'),
    path('orders/<int:pk>/delete/', OrderDeleteView.as_view(), name='order-delete'),
    path('orders/<int:pk>/update/', OrderUpdateView.as_view(), name='order-update'),


]

shopapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):

    class Meta:
        ordering = ['name', 'price']
        # b_table ="tech_products"
        # verbose_name_plural="products"

    name = models.CharField(max_length=100)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.PositiveSmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    created_by=models.ForeignKey(User, on_delete=models.PROTECT)
    
    def __str__(self)-> str:
        return f"Product(pk={self.pk}, name={self.name!r})"

    
class Order(models.Model):
    delivery_adress = models.TextField(null=True, blank=True)
    promocode=models.CharField(max_length=20, null=False, blank=True)
    created_at=models.DateTimeField(auto_now_add=True)
    user=models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product,related_name="orders")
    
    def __str__(self):
         return str(self.pk)

shopapp/forms.py
from django import forms
from django.core import validators
from .models import Product
from django.forms import ModelForm
from django.contrib.auth.models import Group
    


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ["name"]

class ProductUpdateForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "discount"]


    

shopapp/views.py
from timeit import default_timer
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.shortcuts import HttpResponse
from django.http import HttpRequest, JsonResponse
from django.contrib.auth.models import Group
from .models import Product, Order
from .forms import GroupForm

# from django.views import View
from django.views.generic import (
    View,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
    UserPassesTestMixin,
)
from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator


# =========================================================
# 1. Products
# =========================================================
class ProductsListView(ListView):
    model = Product
    context_object_name = "products"
    queryset = model.objects.filter(archived=False)


class ProductDetailView(DetailView):
    model = Product
    context_object_name = "product"


class ProductCreateView(PermissionRequiredMixin, CreateView):
    permission_required = "shopapp.add_product"
    model = Product
    fields = "name", "price", "description", "discount"
    success_url = reverse_lazy("shopapp:product-list")

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class ProductUpdateView(UserPassesTestMixin, UpdateView):
    model = Product
    fields = "name", "price", "discount"
    template_name_suffix = "_update_form"

    def test_func(self):
        if self.request.user.is_superuser:
            return True
        self.object = self.get_object()
        has_edit_perm = self.request.user.has_perm("shopapp.change_product")
        created_by_current_user = self.object.created_by == self.request.user
        return has_edit_perm and created_by_current_user

    def get_success_url(self):
        return reverse(
            "shopapp:product-detail",
            kwargs={"pk": self.object.pk},
        )


class ProductArchivedView(DeleteView):
    model = Product
    template_name = "shopapp/product_confirm_archive.html"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.archived = True
        self.object.save()
        return redirect(
            reverse("shopapp:product-detail", kwargs={"pk": self.object.pk})
        )


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("shopapp:product-list")


# =========================================================
# 2. Orders
# =========================================================


class OrdersListView(LoginRequiredMixin, ListView):
    queryset = Order.objects.select_related("user").prefetch_related("products")


class OrderDetailView(PermissionRequiredMixin, DetailView):
    permission_required = "shopapp.view_order"
    queryset = Order.objects.select_related("user").prefetch_related("products")


class OrderCreateView(CreateView):
    model = Order
    fields = "delivery_adress", "promocode", "user", "products"
    success_url = reverse_lazy("shopapp:order-list")


class OrderUpdateView(UpdateView):
    model = Order
    fields = "delivery_adress", "promocode", "user", "products"
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            "shopapp:order-detail",
            kwargs={"pk": self.object.pk},
        )


class OrderDeleteView(DeleteView):
    model = Order
    # template_name = 'shopapp/order_confirm_delete.html'
    success_url = reverse_lazy("shopapp:order-list")


class ShopIndexView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ("Laptop", 1999),
            ("Desktop", 2999),
            ("Smartfhone", 999),
        ]

        context = {
            "time_running": default_timer(),
            "products": products,
        }

        return render(request, "shopapp/shop-index.html", context=context)


def groups_list(request: HttpRequest):
    context = {"groups": Group.objects.prefetch_related("permissions").all()}
    return render(request, "shopapp/groups-list.html", context=context)


class GroupsListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            "form": GroupForm,
            "groups": Group.objects.prefetch_related("permissions").all(),
        }
        return render(request, "shopapp/groups-list.html", context=context)

    def post(self, request: HttpRequest):
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect(request.path)


class ProductsDataExportView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        products = Product.objects.order_by("pk").all()
        products_data = [
            {
                "pk": product.pk,
                "name": product.name,
                "price": product.price,
                "archived": product.archived,
            }
            for product in products
        ]
        return JsonResponse({"products": products_data})


class OrderExportView(View):
    def test_check_staff(user):
        return user.is_staff

    @method_decorator(user_passes_test(test_check_staff))
    # @method_decorator(staff_member_required)
    def get(self, request: HttpRequest) -> JsonResponse:
        orders = Order.objects.order_by("pk").all()
        orders_data = [
            {
                "ID": order.user.id,
                "delivery_adress": order.delivery_adress,
                "promocode": order.promocode,
                "products": [product.pk for product in order.products.all()],
            }
            for order in orders
        ]
        return JsonResponse({"orders": orders_data})

shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="'UTF-8">
        <Title>
            {% block title %}
                Base Title
            {% endblock %}
        </Title>
    </head>
    
    <body>
        {% block body %}
            Base Body
        {% endblock %}

        <div>
            {% now 'H:i' %}
        </div>

        <div>
            {% now 'l' as current_weekday %}
            Today is {{ current_weekday }}
        </div>
    </body>
</html>

shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create New Product
{% endblock %}

{% block body %}
    <h1> Products </h1>
    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p}}
            
            <button type="submit">
                Create
            </button>
        </form>
    </div> 
    <div>
        <a href={% url 'shopapp:products-list' %}>
        Back to products list
        </a>
    </div
{% endblock %}

shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Group list
{% endblock %}

{% block body %}
    <h1> Groups:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        <ul>
        {% for group in groups %}
            <li>
                <div>{{ group.name }}</div>
                
                <ul>
                    {% for permission in group.permissions.all %}
                    <li>
                        {{ permission.name }}
                        (<code>{{ permission.codename }}</code>)
                    </li>
                    {% endfor %}
                </ul>
                </li>
        {% empty %}
            No group
        {% endfor%}
        </ul>
    </div>
{% endblock %}

shopapp/templates/shopapp/order-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order list
{% endblock %}

{% block body %}
    <h1> Orders: </h1>
    <div>
        {% for order in orders %}
            <div>
               <p> Order by: {% firstof order.user.first_name order.user.username %} </p>
               <p> Promocode: <code>{{ order.promocode}} </code></p>
               <p> Delivery adress: <code>{{ order.delivery_adress}} </code></p>
               <div>
                    <p> Product in order: </p>
                    <ul>
                        {% for product in order.products.all %}
                            <li>{{ product.name }} for $ {{ product.price }}</li>
                        {% endfor %}
                    </ul>   
                </div>
            </div>   
        {% empty %}
            No products yet
        {% endfor%}
    </div>
    <div>
        <a href={% url 'shopapp:order-create' %}>
        Create a new order
        </a>
    </div 
{% endblock %}

shopapp/templates/shopapp/order_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create New Order
{% endblock %}

{% block body %}
    <h1> Order </h1>
    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p}}
            
            <button type="submit">
                Create
            </button>
        </form>
    </div> 
    <div>
        <a href={% url 'shopapp:order-list' %}>
        Back to order list
        </a>
    </div
{% endblock %}

shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order list
{% endblock %}

{% block body %}
    <h1> Orders: </h1>
    <div>
        {% for order in object_list %}
            <div>
               <p><a href={% url 'shopapp:order-detail' pk=order.pk %}>Details # {{ order.pk }}</a></p>
               <p> Order by: {% firstof order.user.first_name order.user.username %} </p>
               <p> Promocode: <code>{{ order.promocode}} </code></p>
               <p> Delivery adress: <code>{{ order.delivery_adress}} </code></p>
               <div>
                    <p> Product in order: </p>
                    <ul>
                        {% for product in order.products.all %}
                            <li>{{ product.name }} for $ {{ product.price }}</li>
                        {% endfor %}
                    </ul>   
                </div>
            </div>   
        {% empty %}
            No products yet
        {% endfor%}
    </div>
    <div>
        <a href={% url 'shopapp:order-create' %}>
        Create a new order
        </a>
    </div 
{% endblock %}

shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update Order
{% endblock %}

{% block body %}
    <h1> Update Order </h1>
    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p}}
            
            <button type="submit">
                Update
            </button>
        </form>
    </div> 
    <div>
        <a href={% url 'shopapp:order-detail' pk=object.pk %}>
        Back to orders # {{ object.pk}}
        </a>
    </div
{% endblock %}

shopapp/templates/shopapp/product_archived_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Archived Product
{% endblock %}

{% block body %}
    <h1> Archived Products </h1>
    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p}}
            
            <button type="submit">
                Archived
            </button>
        </form>
    </div> 
    <div>
        <a href={% url 'shopapp:product-detail' pk=object.pk %}>
        Back to products # {{ object.pk }}
        </a>
    </div
{% endblock %}

shopapp/templates/shopapp/product_confirm_archive.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm to arhive product # {{ product.pk }}
{% endblock %}

{% block body %}
    <h1> Are you sure you want to archive {{ object.name }}?</h1>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            <button type="submit">Confirm</button>
        </form>
        <a href="{% url 'shopapp:product-detail' pk=object.pk %}">Отмена</a>
    </div>
{% endblock %}

shopapp/templates/shopapp/product_confirm_archived.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm to arhive product # {{ product.pk }}
{% endblock %}

{% block body %}
    <h1> Are you sure you want to archive {{ object.name }}?</h1>
    <br>
    <div>
        <a href={% url 'shopapp:product-detail' pk=object.pk %}>Back to product</a>
    </div>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Archive</button>
        </form>
    </div>
{% endblock %}

shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm delete product # {{ product.pk }}
{% endblock %}

{% block body %}
    <h1> Are you sure you want to delete {{ object.name }}?</h1>
    <br>
    <div>
        <a href={% url 'shopapp:product-detail' pk=object.pk %}>Back to product</a>
    </div>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Delete</button>
        </form>
    </div>
{% endblock %}

shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create New Product
{% endblock %}

{% block body %}
    <h1> Create Products </h1>
    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p}}
            
            <button type="submit">
                Create
            </button>
        </form>
    </div> 
    <div>
        <a href={% url 'shopapp:product-list' %}>
        Back to products list
        </a>
    </div
{% endblock %}

shopapp/templates/shopapp/product_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Product list
{% endblock %}

{% block body %}
    <h1> Products </h1>
    <div>
        <table>
            <tr>
                <th>Name</th>
                <th>Price</th>
                <th>Discount</th>
            </tr>
        {% for product in products %}
            <tr>
                <td><a href={% url 'shopapp:product-detail' pk=product.pk %}>{{ product.name }} </a></td>
                <td> {{ product.price}} </td>
                <td> {% firstof product.discount 'no discount'  %} </td>
            </tr>
  
        {% empty %}
            No products here
        {% endfor%}
        </table>
    </div>
    {% if perms.shopapp.add_product %}
        <div>
            <a href={% url 'shopapp:product-create' %}>
            Create a new product
            </a>
        </div
    {% endif %}
{% endblock %}

shopapp/templates/shopapp/product_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update Product
{% endblock %}

{% block body %}
    <h1> Update Products </h1>
    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p}}
            
            <button type="submit">
                Update
            </button>
        </form>
    </div> 
    <div>
        <a href={% url 'shopapp:product-detail' pk=object.pk %}>
        Back to products # {{ object.pk}}
        </a>
    </div
{% endblock %}